### ISSUE TITLE
Missing the installation

### ISSUE THREAD

**Issue by paranpul** [hakkisabah/dinamikfikir#1]
Thank you for distributing a very good CI 4.X source.

The downloaded dinamikfikir-master file is missing the installation related files in the Youtube video or README.md.
Can I get the related files or the table structure of the database?

**Comment by hakkisabah** [comment]
> Thank you for distributing a very good CI 4.X source.
> 
> The downloaded dinamikfikir-master file is missing the installation related files in the Youtube video or README.md.
> Can I get the related files or the table structure of the database?

Hello ,

Thank you for review.

I am ready to do my best if you can explain the problem you faced or what you need. As long as the minimum requirements in the _Linux_ environment are met, there should not be a problem.

Also, `app / Controllers / Setup / Database / Migrations / ForgeMaster.php`

There is also the auto table creation setup file triggered by **ForgeMaster** in the file path.
